name: rawtherapee
version: "4.0.12"
summary: cross-platform raw image processing program
description: |
  Rather than being a raster graphics editor such as Photoshop or GIMP,
  it is specifically aimed at raw photo post-production.
  And it does it very well - at a minimum, RawTherapee is one
  of the most powerful raw processing programs available.

confinement: devmode

apps:
    rawtherapee:
        command: desktop-launch rawtherapee
        plugs: [home, unity7, x11, gsettings]

parts:
    rawtherapee:
        source: https://github.com/dargad/RawTherapee.git
        source-branch: snap
        configflags:
            - -DRUNTIME_DATA_PREFIX=/snap/rawtherapee/current/share/rawtherapee
        plugin: cmake
        build-packages:
            - build-essential
            - cmake
            - curl
            - libbz2-dev
            - libcanberra-gtk3-dev
            - libexiv2-dev
            - libexpat1-dev
            - libfftw3-dev
            - libglibmm-2.4-dev
            - libgtk-3-dev
            - libgtkmm-3.0-dev
            - libiptcdata0-dev
            - libjpeg8-dev
            - liblcms2-dev
            - libpng-dev
            - libsigc++-2.0-dev
            - libtiff5-dev
            - zlib1g-dev
        after: [desktop/gtk3]
